Bug fixes and docs update

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -23,24 +23,26 @@ printf "\n"
 pass_hash=$(echo "$passkey" | md5sum | head -c 10)
 
 # GET ISO PATH
-printf "\033[1mFull path where to create image (directory structure is created if doesn't exist): \033[0m"
+printf "\033[1mPath where to create image: \033[0m"
 read iso_path
 [ -z "$iso_path" ] && printf "\033[31;1mE - Cancelled!\033[0m\n" >&2 && exit 1
 
 # GET MOUNT PATH
-printf "\033[1mMount folder full path (directory structure is created if doesn't exis): \033[0m"
+printf "\033[1mMount folder path: \033[0m"
 read mount_path
 [ -z "$mount_path" ] && printf "\033[31;1mE - Cancelled!\033[0m\n" >&2 && exit 1
 
 # CREATE MOUNT POINT
 [ ! -d "$mount_path" ] && mkdir -p $mount_path 2>/dev/null
 [ ! -d "$mount_path" ] && printf "\033[31;1mE - Couldn't create mount path at '$mount_path'!\033[0m\n" >&2 && exit 1
+mount_path=$(realpath $mount_path)
 
 # PREPARE IMAGE FILE
 [ ! -d "$iso_path" ] && mkdir -p $iso_path 2>/dev/null
 [ ! -d "$iso_path" ] && printf "\033[31;1mE - Couldn't create image path '$iso_path'!\033[0m\n" >&2 && exit 1
+iso_path=$(realpath $iso_path)
 
-image="$(tr -dc '0-9' </dev/urandom | head -c 10).img"
+image="$(tr -dc '0-9A-Z' </dev/urandom | head -c 10).img"
 image_path=$iso_path/$image
 printf "\033[1mImage size in (mb) >=50: \033[0m"
 read iso_size
@@ -152,7 +154,7 @@ while getopts "h?p:k:d:m" opt; do
     h|\\?) printf "\$help"; exit 0;;
     p)  iso_path=\$OPTARG;;
     k)  passkey=\$OPTARG;;
-    d)  dumpfile=\$OPTARGA;;
+    d)  dumpfile=\$OPTARG;;
     m)  mountpath=1;;
     esac
 done
@@ -165,9 +167,10 @@ if [ -z "\$passkey" ]; then
 
 fi
 
+hash=\$(echo "\$passkey" | md5sum | head -c 10)
+
 if [ \$mountpath -eq 1 ]; then
-    hash=\$(echo "\$passkey" | md5sum | head -c 10)
-    [ "\$hash" != "$pass_hash" ] && printf "\033[31;1mE - invalid passkey!\nE - Identity unknown, not today!!!\n\033[0m" >&2 && exit 1
+    [ "\$hash" != "$pass_hash" ] && printf "\033[31;1mE - invalid passkey!\n\033[0m" >&2 && exit 1
     printf "mountPath: $mount_path\n" && exit 0
 fi
 
@@ -175,13 +178,14 @@ printf "\033[33;1mW - sudo may be requred!\n\033[0m"
 
 MAP_POINT=$MAP_POINT
 if [ -z "\$iso_path" ]; then
+    image_path=$image_path
+    [ "\$hash" != "$pass_hash" ] && printf "\033[31;1mE - invalid passkey!\n\033[0m" >&2 && exit 1
+    printf "\033[32;1mI - Hi there `whoami`!\n\033[0m"
+    
     if mount | grep -q "\$MAP_POINT"; then
+        [ -n "\$dumpfile" ] && printf "\033[31;1mE - Image in use!\n\033[0m" >&2 && exit 1
         printf "\033[33;1mW - All set security may have been compromised!\n\033[0m" && exit 0
     fi
-    image_path=$image_path
-    hash=\$(echo "\$passkey" | md5sum | head -c 10)
-    [ "\$hash" != "$pass_hash" ] && printf "\033[31;1mE - invalid passkey!\nE - Identity unknown, not today!!!\n\033[0m" >&2 && exit 1
-    printf "\033[32;1mI - Hi there mr `whoami`!\n\033[0m"
 else
     if [ -f \$iso_path ]; then
         image_path=\$(realpath \$iso_path)
@@ -197,20 +201,22 @@ if [ -f \$image_path ]; then
     [ \$? -ne 0 ] && printf "\033[31;1mE - Could not decrypt data!\033[0m\n" >&2 && exit 1
 else
     printf "\033[33;1mW - Image missing!\033[0m\n" >&2
-    printf "\033[1mEnter full path to image: \033[0m"
+    printf "\033[1mEnter path to image: \033[0m"
     read image_path
     [ ! -f "\$image_path" ] && printf "\033[31;1mE - Invalid path!\033[0m\n" >&2 && exit 1
     printf "\033[34;1mI - Opening ...\033[0m\n\033[0m"
+    image_path=\$(realpath \$image_path)
     echo "\$passkey@\`whoami\`" | md5sum | head -c 12 | sudo cryptsetup luksOpen \$image_path \$MAP_POINT
     [ \$? -ne 0 ] && printf "\033[31;1mE - Error decrypting, maybe not the target iso!\033[0m\n" >&2 && exit 1
 fi
 
 if [ -n "\$dumpfile" ]; then
     printf "\033[34;1mI - Dumping key to "\$dumpfile" ...\033[0m\n"
-    echo "path: \$(realpath \$image_path)" > \$dumpfile
-    echo "owner: \$(whoami)" >> \$dumpfile
+    echo "owner: \$(whoami)" > \$dumpfile
+    echo "image path: \$(realpath \$image_path)" >> \$dumpfile
+    echo "mount path: $mount_path" >> \$dumpfile
     echo "key: \`echo \$passkey@\$(whoami) | md5sum | head -c 12\`" >> \$dumpfile
-    sudo cryptsetup luckClose \$MAP_POINT >/dev/null 2>&1
+    sudo cryptsetup luksClose \$MAP_POINT >/dev/null 2>&1
     printf "\033[34;1mI - Key dumped!\033[0m\n"
     exit 0
 fi
@@ -262,7 +268,6 @@ else
 fi
 
 if ! mount | grep -q "\$MAP_POINT"; then
-    sudo cryptsetup luckClose \$MAP_POINT >/dev/null 2>&1
     printf "\033[33;1mW - All set nothing to configure!\n\033[0m" && exit 0
 fi
 
