Recovery mode added

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -3,8 +3,8 @@
 
 # CONFIRM ALL DEPENDENCIES
 printf "\033[34;1m[x] Confirming dependencies ...\033[0m"
-which sudo shc cryptsetup file >/dev/null
-[ $? -ne 0 ] && printf "\033[31;1m\nE - missing dependencies ensure {which sudo shc cryptsetup file} are all installed!\033[0m\n" >&2 && exit 1
+which sudo shc cryptsetup md5sum file >/dev/null
+[ $? -ne 0 ] && printf "\033[31;1m\nE - missing depencencies ensure {which sudo shc md5sum cryptsetup file} are all installed!\033[0m\n" >&2 && exit 1
 printf " ✅\n"
 
 # GET PASSKEY
@@ -28,7 +28,7 @@ read iso_path
 [ -z "$iso_path" ] && printf "\033[31;1mE - Cancelled!\033[0m\n" >&2 && exit 1
 
 # GET MOUNT PATH
-printf "\033[1mMount folder full path (directory structure is created if doesn't exits): \033[0m"
+printf "\033[1mMount folder full path (directory structure is created if doesn't exis): \033[0m"
 read mount_path
 [ -z "$mount_path" ] && printf "\033[31;1mE - Cancelled!\033[0m\n" >&2 && exit 1
 
@@ -44,7 +44,7 @@ image="$(tr -dc '0-9' </dev/urandom | head -c 10).img"
 image_path=$iso_path/$image
 printf "\033[1mImage size in (mb) >=50: \033[0m"
 read iso_size
-[ $iso_size -lt 50 ] && printf "\033[31;1mE - Ensure at least 50 mb!\033[0m\n" >&2 && exit 1
+[ $iso_size -lt 50 ] && printf "\033[31;1mE - Ensure atleast 50 mb!\033[0m\n" >&2 && exit 1
 
 dd if=/dev/zero of=$image_path bs=1M count=$iso_size status=progress
 [ $? -ne 0 ] && exit 1
@@ -52,12 +52,12 @@ dd if=/dev/zero of=$image_path bs=1M count=$iso_size status=progress
 # ENCRYPT THE IMAGE
 printf "\n\033[34;1m[x] Encrypting image ...\033[0m"
 echo "$passkey@`whoami`" | md5sum | head -c 12 | cryptsetup luksFormat $image_path --batch-mode
-[ $? -ne 0 ] && printf "\033[31;1m\nE - Error encrypting image!\033[0m\n" >&2 && exit 1
+[ $? -ne 0 ] && printf "\033[31;1m\nE - Error enrypting image!\033[0m\n" >&2 && exit 1
 printf " ✅\n"
 
 # CONFIGURING IMAGE
 printf "\033[34;1m[x] Configuring image ... ✅\n\033[0m"
-printf "\033[33;1mW - sudo may be required!\n\033[0m"
+printf "\033[33;1mW - sudo may be requred!\n\033[0m"
 USER=`whoami`
 MAP_POINT=$(tr -dc 'A-Za-z0-9' </dev/urandom | head -c 10)
 echo "$passkey@`whoami`" | md5sum | head -c 12 | sudo cryptsetup luksOpen $image_path $MAP_POINT
@@ -68,7 +68,7 @@ sudo mount /dev/mapper/$MAP_POINT $mount_path >/dev/null 2>&1
 sudo chown $USER:$USER $mount_path
 mkdir $mount_path/{downloads,backup}
 
-# SCRAPE ISO INFORMATION
+# SCRAPE ISO INFOMATION
 RAW_OUTPUT=$(file $image_path)
 file_name=$(echo "$RAW_OUTPUT" | grep -oP '^\S+')
 version=$(echo "$RAW_OUTPUT" | grep -oP 'ver \K\d+')
@@ -99,7 +99,7 @@ Encrypted ISO Image Information
 Key Slots: $keyslots_json
 
 ------------------------------
-Ownership Information
+Ownership Infomation
 ------------------------------
 - File owner: `whoami`
 - File Size: $iso_size MB
@@ -108,13 +108,13 @@ Ownership Information
 - Image Path: $image_path
 
 ------------------------------
-Author Information
+Author Infomation
 ------------------------------
 - Name: Alpinine99
 - github: https://github.com/Alpinine99/2f-encryption.git
 
 ------------------------------
-Other Information
+Other Infomation
 ------------------------------
 - No available passkey backup.
 - Handle with care to maintain security.
@@ -133,22 +133,62 @@ cat > mapper <<EOF
 
 [ \`id -u\` -ne `id -u` ] && exit 1
 
+help="\\
+    This binary decrypts and maps you data to the compiled folder.
+    You can specify a image path -p <full path>, if you moved your image and passkey -k in batch mode else prompted.
+    Example:    \$0 -p /home/user/downloads/7565625236.img -k 1234e
+"
+
+passkey=""
+iso_path=""
+while getopts "h?p:k:" opt; do
+  case "\$opt" in
+    h|\\?) printf "\$help"; exit 0;;
+    p)  iso_path=\$OPTARG;;
+    k)  passkey=\$OPTARG;;
+    esac
+done
+
 if mount | grep -q "$MAP_POINT"; then
     printf "\033[33;1mW - All set security may have been compromised!\n\033[0m" && exit 0
 fi
 
-printf "\033[33;1mW - 2F authentication required!\n\033[0m"
-printf "\033[1mPasskey: \033[0m"
-read -s passkey
-printf "\n"
+if [ -z "\$passkey" ]; then
+    printf "\033[33;1mW - 2F authentication required!\n\033[0m"
+    printf "\033[1mPasskey: \033[0m"
+    read -s passkey
+    printf "\n"
 
-hash=\$(echo "\$passkey" | md5sum | head -c 10)
+fi
 
-[ "\$hash" != "$pass_hash" ] && printf "\033[31;1mE - invalid passkey!\nE - Identity unknown, not today!!!\n\033[0m" >&2 && exit 1
-printf "\033[32;1mI - Hi there mr `whoami`!\n\033[0m"
-printf "\033[33;1mW - sudo may be required!\n\033[0m"
-printf "\033[34;1mI - Opening ...\033[0m\n\033[0m"
-echo "\$passkey@\`whoami\`" | md5sum | head -c 12 | sudo cryptsetup luksOpen $image_path $MAP_POINT
+printf "\033[33;1mW - sudo may be requred!\n\033[0m"
+
+if [ -z "\$iso_path" ]; then
+    image_path=$image_path
+    hash=\$(echo "\$passkey" | md5sum | head -c 10)
+    [ "\$hash" != "$pass_hash" ] && printf "\033[31;1mE - invalid passkey!\nE - Identity unknown, not today!!!\n\033[0m" >&2 && exit 1
+    printf "\033[32;1mI - Hi there mr `whoami`!\n\033[0m"
+else
+    if [ -f \$iso_path ]; then
+        image_path=\$iso_path
+    else
+        printf "\033[31;1mE - Invalid path!\033[0m\n" >&2 && exit 1
+    fi
+fi
+
+if [ -f \$image_path ]; then
+    printf "\033[34;1mI - Opening ...\033[0m\n\033[0m"
+    echo "\$passkey@\`whoami\`" | md5sum | head -c 12 | sudo cryptsetup luksOpen \$image_path $MAP_POINT
+    [ \$? -ne 0 ] && printf "\033[31;1mE - Could not decrypt data!\033[0m\n" >&2 && exit 1
+else
+    printf "\033[33;1mW - Image missing!\033[0m\n" >&2
+    printf "\033[1mEnter full path to image: \033[0m"
+    read iso_path
+    [ ! -f "\$iso_path" ] && printf "\033[31;1mE - Invalid path!\033[0m\n" >&2 && exit 1
+    printf "\033[34;1mI - Opening ...\033[0m\n\033[0m"
+    echo "\$passkey@\`whoami\`" | md5sum | head -c 12 | sudo cryptsetup luksOpen \$iso_path $MAP_POINT
+    [ \$? -ne 0 ] && printf "\033[31;1mE - Error decrypting, maybe not the target iso!\033[0m\n" >&2 && exit 1
+fi
 
 mkdir $mount_path 2>/dev/null
 sudo mount /dev/mapper/$MAP_POINT $mount_path >/dev/null 2>&1
@@ -166,20 +206,47 @@ printf "\033[34;1m[x] Generating umapper source code ...\033[0m"
 cat >umapper <<EOF
 #! `which bash`
 
-printf "\033[33;1mW - sudo may be required!\n\033[0m"
+help="\\
+    This binary encrypts and unmaps you data from compiled folder.
+    You can specify a folder path -p <full path>, if you are unmapping a different data point.
+    Example:    \$0 -p /home/user/downloads
+"
 
-if ! mount | grep -q "$MAP_POINT"; then
-    sudo cryptsetup close $image_path >/dev/null 2>&1
+mount_path=""
+MAP_POINT=""
+while getopts "h?p:k:" opt; do
+  case "\$opt" in
+    h|\\?) printf "\$help"; exit 0;;
+    p)  mount_path=\$OPTARG;;
+    esac
+done
+
+printf "\033[33;1mW - sudo may be requred!\n\033[0m"
+
+if [ -z "\$mount_path" ]; then
+    mount_path=$mount_path
+    MAP_POINT=$MAP_POINT
+else
+    [ ! -d \$mount_path ] && printf "\033[31;1mE - Invalid path!\033[0m\n" >&2 && exit 1
+    if mount | grep -q "\$mount_path"; then
+        MAP_POINT=\`mount | grep "\$mount_path" | cut -f1 -d' '\`
+    else
+        printf "\033[33;1mW - All set nothing to configure!\n\033[0m" && exit 0
+    fi
+fi
+
+if ! mount | grep -q "\$MAP_POINT"; then
+    sudo cryptsetup luckClose \$MAP_POINT >/dev/null 2>&1
     printf "\033[33;1mW - All set nothing to configure!\n\033[0m" && exit 0
 fi
 
 sudo sync
 sleep .3
 
-sudo umount $mount_path >/dev/null 2>&1
+sudo umount \$mount_path >/dev/null 2>&1
 [ \$? -ne 0 ] && printf "\033[31;1mE - Unsuccessful config!\033[0m\n" >&2 && exit 1
 
-sudo cryptsetup luksClose $MAP_POINT >/dev/null 2>&1
+sudo cryptsetup luksClose \$MAP_POINT >/dev/null 2>&1
 [ \$? -ne 0 ] && printf "\033[31;1mE - Unsuccessful config!\033[0m\n" >&2 && exit 1
 
 printf "\033[32;1mI - Successful config\n\033[0m"
@@ -188,6 +255,6 @@ exit 0
 EOF
 printf " ✅\n"
 
-# FINISH UP
+# FINISHUP
 printf "\033[34;1m[x] Configuration successful \033[0m✅\n"
 exit 0
